services:
  - type: web
    name: token-launcher-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SEED_PHRASE
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SOLANA_RPC_URL
        value: https://api.mainnet-beta.solana.com
      - key: HELIUS_RPC_URL
        sync: false
      - key: TOKEN_NAME
        value: MyToken
      - key: TOKEN_SYMBOL
        value: MTK
      - key: TOKEN_DECIMALS
        value: "9"
      - key: TOKEN_SUPPLY
        value: "1000000000"
