services:
  - type: web
    name: token-launcher-bot
    runtime: python
    plan: standard
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: RENDER_EXTERNAL_URL
        fromService:
          name: token-launcher-bot
          type: web
          property: url
      - key: SEED_PHRASE
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: JUPITER_API_KEY
        sync: false
      - key: HELIUS_API_KEY
        sync: false
